# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- powershell: (Get-WmiObject Win32_Processor).VirtualizationFirmwareEnabled[0]
- powershell: (Get-WmiObject Win32_Processor).SecondLevelAddressTranslationExtensions[0]
- script: docker images
- powershell: |
    $destPath = "$(pwd)\diskspd"
    $zipPath = "$env:TEMP\DiskSpd-2.0.21a.zip"
    (New-Object Net.WebClient).DownloadFile('https://gallery.technet.microsoft.com/DiskSpd-A-Robust-Storage-6ef84e62/file/199535/2/DiskSpd-2.0.21a.zip', $zipPath)
    7z x $zipPath -aoa -o"$destPath"
    dir
    & .\diskspd\amd64\diskspd -c1G -d60 -r -w40 -t2 -o32 -b64K -Sh -L C:\testfile1.dat
    & .\diskspd\amd64\diskspd -c1G -d60 -r -w40 -t2 -o32 -b64K -Sh -L D:\testfile1.dat

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: node --version
  displayName: 'test node version'

- script: yarn install --frozen-lockfile
  displayName: 'yarn install'

- script: yarn lint
  displayName: 'yarn lint'
  
- script: yarn build
  displayName: 'yarn build'
  
- script: yarn test
  displayName: 'yarn test'

- script: yarn prettier
  displayName: 'yarn prettier'
